### ISSUE TITLE
QUESTION: I don't know what to title this question.

### ISSUE THREAD

**Issue by ghost** [Banane9/IronWren#2]
If I'm going to be using this in the context of a game, I'm going to need to be able to block calls which I don't want it to make (such as file IO).
Basically, I need to be the sole provider for any API beyond what's included with wren. Is it possible to block stuff like this? Sorry if this isn't the place to ask questions, but I couldn't figure it out on my own ;).

**Comment by Banane9** [comment]
Well, IronWren provides no API to Wren by itself, so everything is entirely under your control :)

**Comment by ghost** [comment]
Actually, ironwren exposing an api wasn't my concern. Wren modules themselves can do stuff on their own, can't they? Like calling into a C library or something?

**Comment by Banane9** [comment]
Well, if they try to import a module or declare foreign classes or functions, there'll be a callback to WrenLoadModule/WrenBindForeignClass/WrenBindForeignFunction.

It can't do anything by itself without going through the host app.

**Comment by ghost** [comment]
K, that should be good enough. I can implement a whitelist or something then.

Thanks!

**Comment by Banane9** [comment]
Well, if you use the AutoMapper, only types you specifically make available will be accessible :)

**Comment by ghost** [comment]
I was going to make this a separate question, but oh well. Is there a way to import types besides using the automapper? Also wondering if I can set variables from my c# host?

**Comment by Banane9** [comment]
Well, you'd have to write your own wrapping code, then :)

The API doesn't really expose something to set variables... though it might work if you get one and then set the value of the slot you loaded it into. Alternatively, you could use Interpret.

**Comment by ghost** [comment]
Hmmm, using interpret wouldn't allow scripts and my game to share references.

And as far as implementing my own wrapper goes, I'll try it :). I'd much rather import by type rather than by type + attributes. In other words, in my implementation, the attributes would be optional.
