### ISSUE TITLE
Using in unity

### ISSUE THREAD

**Issue by cemuka** [Banane9/IronWren#7]
Firstly, I tried on my both m1 mac and windows machine in unity but I got DllNotFoundException. I thought its a path issue but console example worked on windows using "dotnet run" (it didn't on mac).

**Comment by Banane9** [comment]
Not sure where it expects the DLL to be when using it with Unity 🤔

**Comment by cemuka** [comment]
I compiled wren from its source as dylib and it worked. Now I can execute wren from unity on macos. But I couldn't get used to embedding and bindings. Example classes (Vector3, Math) helped a bit but I need more time to learn it I guess. 

So issue solved but looking forward to easier examples for embedding  :)

**Comment by Banane9** [comment]
Yeaaaa, that whole integration thing is quite old 😅

**Comment by cemuka** [comment]
Any plans for a new update? I could be the unity test guy 😎
